# Generated by Django 3.2.3 on 2024-07-11 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20240711_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
    ]
