# Generated by Django 3.2.3 on 2024-07-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_auto_20240711_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientReceipt',
            new_name='IngredientInReceipt',
        ),
    ]
