# Generated by Django 3.2.3 on 2024-07-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_rename_ingredientreceipt_ingredientinreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_receipt', to='receipts.receipt'),
        ),
    ]
