# Generated by Django 3.2.3 on 2024-07-10 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_user_favourites',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_shopping_cart',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=16, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredientreceipt',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Мера'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ingredients',
            field=models.ManyToManyField(through='receipts.IngredientReceipt', to='receipts.Ingredient', verbose_name='Продукты в рецепте'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
