# Generated by Django 3.2.3 on 2024-07-11 19:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_user_favourites',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_shopping_cart',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_follower_following',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='following',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='short_link',
        ),
        migrations.AlterField(
            model_name='favourite',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='receipts.receipt'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=16, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredientreceipt',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Мера'),
        ),
        migrations.AlterField(
            model_name='ingredientreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_list', to='receipts.receipt'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='receipts.IngredientReceipt', to='receipts.Ingredient', verbose_name='Продукты в рецепте'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='receipts.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcarts', to='receipts.receipt'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcarts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z')]),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('follower', 'author'), name='unique_follower_author'),
        ),
    ]
