# Generated by Django 3.2.3 on 2024-07-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_ingredientinreceipt_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinreceipt',
            options={'verbose_name': 'Продукт в рецепте', 'verbose_name_plural': 'продукты в рецепте'},
        ),
    ]
