# Generated by Django 3.2.3 on 2024-07-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20240711_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'default_related_name': 'favorites', 'verbose_name': 'Избранное', 'verbose_name_plural': 'избранные'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'default_related_name': 'ingredients', 'verbose_name': 'Продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_carts', 'verbose_name': 'Корзина покупок', 'verbose_name_plural': 'корзины покупок'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'default_related_name': 'subscriptions', 'verbose_name': 'Подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'verbose_name': 'Тег', 'verbose_name_plural': 'теги'},
        ),
    ]
