# Generated by Django 3.2.3 on 2024-06-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20240620_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientreceipt',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
