# Generated by Django 3.2.3 on 2024-07-11 14:55
from django.core.validators import RegexValidator
from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20240710_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='short_link',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=(RegexValidator(r'^[\w.@+-]+\Z'),),),
        ),
    ]
