# Generated by Django 3.2.3 on 2024-06-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_ingredientreceipt_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-published_at'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'рецепты'},
        ),
    ]
