# Generated by Django 3.2.3 on 2024-07-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20240713_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinreceipt',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.ingredient', verbose_name='Продукт'),
        ),
    ]
