# Generated by Django 3.2.3 on 2024-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_alter_receipt_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='receipts.IngredientReceipt', to='receipts.Ingredient', verbose_name='Продукты в рецепте'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='receipts.Tag', verbose_name='Теги'),
        ),
    ]
