# Generated by Django 3.2.3 on 2024-07-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_alter_ingredientinreceipt_ingredient'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ingredientinreceipt',
            index=models.Index(fields=['ingredient'], name='receipts_in_ingredi_59b49d_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientinreceipt',
            index=models.Index(fields=['receipt'], name='receipts_in_receipt_8e95a2_idx'),
        ),
    ]
