# Generated by Django 3.2.3 on 2024-06-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_rename_time_receipt_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='title',
            new_name='name',
        ),
    ]
