# Generated by Django 3.2.3 on 2024-07-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_auto_20240714_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinreceipt',
            options={'default_related_name': 'ingredients_in_receipts', 'verbose_name': 'Продукт в рецепте', 'verbose_name_plural': 'продукты в рецепте'},
        ),
        migrations.AlterField(
            model_name='ingredientinreceipt',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_receipts', to='receipts.ingredient', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='ingredientinreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_receipts', to='receipts.receipt', verbose_name='Рецепт'),
        ),
    ]
