# Generated by Django 3.2.3 on 2024-07-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_auto_20240711_2242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'receipt')},
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('user', 'receipt')},
        ),
    ]
