# Generated by Django 3.2.3 on 2024-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_receipt_is_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
