# Generated by Django 3.2.3 on 2024-06-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0010_receipt_is_in_shopping_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='description',
            new_name='text',
        ),
    ]
