# Generated by Django 3.2.3 on 2024-06-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0013_auto_20240623_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
