# Generated by Django 3.2.3 on 2024-07-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0017_auto_20240702_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
