# Generated by Django 3.2.3 on 2024-07-05 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0020_alter_receipt_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(upload_to='receipt/images'),
        ),
    ]
