# Generated by Django 3.2.3 on 2024-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0027_auto_20240708_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=16, verbose_name='Мера'),
        ),
    ]
