# Generated by Django 3.2.3 on 2024-06-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_alter_receipt_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='time',
            new_name='cooking_time',
        ),
    ]
