# Generated by Django 3.2.3 on 2024-06-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_rename_title_receipt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
