# Generated by Django 3.2.3 on 2024-06-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_rename_title_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_favorited',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
    ]
