# Generated by Django 3.2.3 on 2024-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredientreceipt',
            name='count',
        ),
        migrations.AddField(
            model_name='ingredientreceipt',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
