# Generated by Django 3.2.3 on 2024-07-01 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0015_auto_20240701_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientreceipt',
            name='amount',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='Количество'),
        ),
    ]
