# Generated by Django 3.2.3 on 2024-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0018_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='short_link',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
