# Generated by Django 3.2.3 on 2024-07-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0021_auto_20240705_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='is_in_shopping_cart',
        ),
    ]
