# Generated by Django 3.2.3 on 2024-07-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0023_alter_shoppingcart_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='short_link',
            field=models.CharField(default='', max_length=3, unique=True),
        ),
    ]
